/*
 *  __  __      _           _      _   ___ _                        
 * |  \/  |__ _| |_ ___ _ _(_)__ _| | | _ ) |___  __ _ __ _ ___ _ _ 
 * | |\/| / _` |  _/ -_) '_| / _` | | | _ \ / _ \/ _` / _` / -_) '_|
 * |_|  |_\__,_|\__\___|_| |_\__,_|_| |___/_\___/\__, \__, \___|_|  
 *                                               |___/|___/     
 *
 * Script For Material Blogger By Dihak - Bloggerku.com
*/
$(document).ready(function(){var e=$("a.blog-pager-older-link").attr("href");$("a.blog-pager-older-link").load(e+" .post-title:first",function(){var e=$("a.blog-pager-older-link").text();$("a.blog-pager-older-link").text(e+"»")});var r=$("a.blog-pager-newer-link").attr("href");$("a.blog-pager-newer-link").load(r+" .post-title:first",function(){var e=$("a.blog-pager-newer-link:first").text();$("a.blog-pager-newer-link").text("«"+e)})});
var randomRelatedIndex,showRelatedPost;!function(e,t,a){var l={widgetTitle:"<h4 class='judul-bawah'><span>Related Post</span></h4>",numPosts:realated,summaryLength:370,titleLength:"auto",thumbnailSize:200,noImage:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAA3NCSVQICAjb4U/gAAAADElEQVQImWOor68HAAL+AX7vOF2TAAAAAElFTkSuQmCC",containerId:"related-post",newTabLink:!1,callBack:function(){}},n=function(e){var l=t.createElement("script");l.type="text/javascript",l.src=e,a.appendChild(l)},r=function(e,t){return Math.floor(Math.random()*(t-e+1))+e},s=function(e){var t,a,l=e.length;if(0===l)return!1;for(;--l;)t=Math.floor(Math.random()*(l+1)),a=e[l],e[l]=e[t],e[t]=a;return e},i="object"==typeof labelArray&&labelArray.length>0?"/-/"+s(labelArray)[0]:"",o=function(e){var t=e.feed.openSearch$totalResults.$t-l.numPosts,a=r(1,t>0?t:1);n("/feeds/posts/summary"+i+"?alt=json-in-script&orderby=updated&start-index="+a+"&max-results="+l.numPosts+"&callback=showRelatedPost")},d=function(e){var t,a,n,r,i,o=document.getElementById(l.containerId),d=s(e.feed.entry),m=l.widgetTitle+'<ul class="related-post">',u=l.newTabLink?' target="_blank"':"",c='<span style="display:block;clear:both;"></span>';if(o){for(var h=0;h<l.numPosts&&h!=d.length;h++){a=d[h].title.$t,n="auto"!==l.titleLength&&l.titleLength<a.length?a.substring(0,l.titleLength)+"&hellip;":a,r="media$thumbnail"in d[h]&&l.thumbnailSize!==!1?d[h].media$thumbnail.url.replace(/\/s[0-9]+(\-c)?\//,"/s"+l.thumbnailSize+"-c/"):l.noImage,i="summary"in d[h]&&l.summaryLength>0?d[h].summary.$t.replace(/<br ?\/?>/g," ").replace(/<.*?>/g,"").replace(/[<>]/g,"").substring(0,l.summaryLength)+"&hellip;":"";for(var A=0,g=d[h].link.length;g>A;A++)t="alternate"==d[h].link[A].rel?d[h].link[A].href:"#";m+='<li class="related-post-item" tabindex="0"><div class="related-post-item-inner"><a class="related-post-item-title" href="'+t+'"'+u+'><img alt="" class="related-post-item-thumbnail" src="'+r+'" width="'+l.thumbnailSize+'" height="'+l.thumbnailSize+'"></a><a class="related-post-item-title" title="'+a+'" href="'+t+'"'+u+">"+n+"</a>"+c+"</div></li>"}o.innerHTML=m+=c+"</ul>",l.callBack()}};randomRelatedIndex=o,showRelatedPost=d,n("/feeds/posts/summary"+i+"?alt=json-in-script&orderby=updated&max-results=0&callback=randomRelatedIndex")}(window,document,document.getElementsByTagName("head")[0]);
